### PR TITLE
feat: support farm

### PR DESCRIPTION
**Pull request by ErKeLost**
### Description

Farm wants to use `isolated-decl` as a type build for `farm js plugin` and to enhance the adaptability of `unplugin`

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Looks like type checking is failed.

**Review by sxzz — APPROVED** [review]

**Comment by ErKeLost** [comment]
> It seems farm ships `.ts` files instead of `.d.ts` files, causing dts errors in `node_modules`.

I fixed this problem on the farm side because the runtime system of the farm does not need to be built, which caused this problem.

**Comment by ErKeLost** [comment]
@sxzz PTAL❤️ Thanks!

**Comment by sxzz** [comment]
@ErKeLost Could you please add unit tests for Farm to prevent accidental breaks?

**Pull request merged**
